/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDetails {
  #[serde(rename = "user_name", skip_serializing_if = "Option::is_none")]
  pub user_name: Option<String>,
  #[serde(rename = "is_reserved", skip_serializing_if = "Option::is_none")]
  pub is_reserved: Option<bool>,
  #[serde(rename = "is_hidden", skip_serializing_if = "Option::is_none")]
  pub is_hidden: Option<bool>,
  #[serde(rename = "is_internal_user", skip_serializing_if = "Option::is_none")]
  pub is_internal_user: Option<bool>,
  #[serde(rename = "user_requested_tenant", skip_serializing_if = "Option::is_none")]
  pub user_requested_tenant: Option<String>,
  #[serde(rename = "backend_roles", skip_serializing_if = "Option::is_none")]
  pub backend_roles: Option<Vec<String>>,
  #[serde(rename = "custom_attribute_names", skip_serializing_if = "Option::is_none")]
  pub custom_attribute_names: Option<Vec<String>>,
  #[serde(rename = "tenants", skip_serializing_if = "Option::is_none")]
  pub tenants: Option<Box<crate::models::UserTenants>>,
  #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
  pub roles: Option<Vec<String>>,
}

impl AccountDetails {
  pub fn new() -> AccountDetails {
    AccountDetails {
      user_name: None,
      is_reserved: None,
      is_hidden: None,
      is_internal_user: None,
      user_requested_tenant: None,
      backend_roles: None,
      custom_attribute_names: None,
      tenants: None,
      roles: None,
    }
  }
}
