/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditConfig {
  #[serde(rename = "compliance", skip_serializing_if = "Option::is_none")]
  pub compliance: Option<Box<crate::models::ComplianceConfig>>,
  #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
  pub enabled: Option<bool>,
  #[serde(rename = "audit", skip_serializing_if = "Option::is_none")]
  pub audit: Option<Box<crate::models::AuditLogsConfig>>,
}

impl AuditConfig {
  pub fn new() -> AuditConfig {
    AuditConfig {
      compliance: None,
      enabled: None,
      audit: None,
    }
  }
}
