/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClusterRerouteMetricMember {
  #[serde(rename = "_all")]
  All,
  #[serde(rename = "blocks")]
  Blocks,
  #[serde(rename = "metadata")]
  Metadata,
  #[serde(rename = "nodes")]
  Nodes,
  #[serde(rename = "routing_table")]
  RoutingTable,
  #[serde(rename = "master_node")]
  MasterNode,
  #[serde(rename = "cluster_manager_node")]
  ClusterManagerNode,
  #[serde(rename = "version")]
  Version,
}

impl ToString for ClusterRerouteMetricMember {
  fn to_string(&self) -> String {
    match self {
      Self::All => String::from("_all"),
      Self::Blocks => String::from("blocks"),
      Self::Metadata => String::from("metadata"),
      Self::Nodes => String::from("nodes"),
      Self::RoutingTable => String::from("routing_table"),
      Self::MasterNode => String::from("master_node"),
      Self::ClusterManagerNode => String::from("cluster_manager_node"),
      Self::Version => String::from("version"),
    }
  }
}

impl Default for ClusterRerouteMetricMember {
  fn default() -> ClusterRerouteMetricMember {
    Self::All
  }
}
