/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterPutSettingsResponseContent {
  #[serde(rename = "acknowledged", skip_serializing_if = "Option::is_none")]
  pub acknowledged: Option<bool>,
  #[serde(rename = "persistent", skip_serializing_if = "Option::is_none")]
  pub persistent: Option<::std::collections::HashMap<String, serde_json::Value>>,
  #[serde(rename = "transient", skip_serializing_if = "Option::is_none")]
  pub transient: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl ClusterPutSettingsResponseContent {
  pub fn new() -> ClusterPutSettingsResponseContent {
    ClusterPutSettingsResponseContent {
      acknowledged: None,
      persistent: None,
      transient: None,
    }
  }
}
