/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

/// ExpandWildcards : Whether to expand wildcard expression to concrete indices
/// that are open, closed or both.

/// Whether to expand wildcard expression to concrete indices that are open,
/// closed or both.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExpandWildcards {
  #[serde(rename = "all")]
  All,
  #[serde(rename = "open")]
  Open,
  #[serde(rename = "closed")]
  Closed,
  #[serde(rename = "hidden")]
  Hidden,
  #[serde(rename = "none")]
  None,
}

impl ToString for ExpandWildcards {
  fn to_string(&self) -> String {
    match self {
      Self::All => String::from("all"),
      Self::Open => String::from("open"),
      Self::Closed => String::from("closed"),
      Self::Hidden => String::from("hidden"),
      Self::None => String::from("none"),
    }
  }
}

impl Default for ExpandWildcards {
  fn default() -> ExpandWildcards {
    Self::All
  }
}
