/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndicesDeleteResponseContent {
  #[serde(rename = "acknowledged", skip_serializing_if = "Option::is_none")]
  pub acknowledged: Option<bool>,
}

impl IndicesDeleteResponseContent {
  pub fn new() -> IndicesDeleteResponseContent {
    IndicesDeleteResponseContent { acknowledged: None }
  }
}
