/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoResponseContent {
  #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
  pub name: Option<String>,
  #[serde(rename = "cluster_name", skip_serializing_if = "Option::is_none")]
  pub cluster_name: Option<String>,
  #[serde(rename = "cluster_uuid", skip_serializing_if = "Option::is_none")]
  pub cluster_uuid: Option<String>,
  #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
  pub version: Option<Box<crate::models::InfoVersion>>,
  #[serde(rename = "tagline", skip_serializing_if = "Option::is_none")]
  pub tagline: Option<String>,
}

impl InfoResponseContent {
  pub fn new() -> InfoResponseContent {
    InfoResponseContent {
      name: None,
      cluster_name: None,
      cluster_uuid: None,
      version: None,
      tagline: None,
    }
  }
}
