/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

/// NodesStatLevel : Return indices stats aggregated at index, node or shard
/// level.

/// Return indices stats aggregated at index, node or shard level.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NodesStatLevel {
  #[serde(rename = "indices")]
  Indices,
  #[serde(rename = "node")]
  Node,
  #[serde(rename = "shards")]
  Shards,
}

impl ToString for NodesStatLevel {
  fn to_string(&self) -> String {
    match self {
      Self::Indices => String::from("indices"),
      Self::Node => String::from("node"),
      Self::Shards => String::from("shards"),
    }
  }
}

impl Default for NodesStatLevel {
  fn default() -> NodesStatLevel {
    Self::Indices
  }
}
