/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteStoreRestoreResponseContent {
  #[serde(rename = "accepted", skip_serializing_if = "Option::is_none")]
  pub accepted: Option<bool>,
  #[serde(rename = "remote_store", skip_serializing_if = "Option::is_none")]
  pub remote_store: Option<Box<crate::models::RemoteStoreRestoreInfo>>,
}

impl RemoteStoreRestoreResponseContent {
  pub fn new() -> RemoteStoreRestoreResponseContent {
    RemoteStoreRestoreResponseContent {
      accepted: None,
      remote_store: None,
    }
  }
}
