/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteStoreRestoreShardsInfo {
  #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
  pub total: Option<i32>,
  #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
  pub failed: Option<i32>,
  #[serde(rename = "successful", skip_serializing_if = "Option::is_none")]
  pub successful: Option<i32>,
}

impl RemoteStoreRestoreShardsInfo {
  pub fn new() -> RemoteStoreRestoreShardsInfo {
    RemoteStoreRestoreShardsInfo {
      total: None,
      failed: None,
      successful: None,
    }
  }
}
