/*
 * OpenSearch
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2021-11-23
 *
 * Generated by: https://openapi-generator.tech
 */

/// WaitForStatus : Wait until cluster is in a specific state.

/// Wait until cluster is in a specific state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WaitForStatus {
  #[serde(rename = "green")]
  Green,
  #[serde(rename = "yellow")]
  Yellow,
  #[serde(rename = "red")]
  Red,
}

impl ToString for WaitForStatus {
  fn to_string(&self) -> String {
    match self {
      Self::Green => String::from("green"),
      Self::Yellow => String::from("yellow"),
      Self::Red => String::from("red"),
    }
  }
}

impl Default for WaitForStatus {
  fn default() -> WaitForStatus {
    Self::Green
  }
}
