/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletedModel {
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "model_id")]
    pub model_id: String,
}

impl DeletedModel {
    
    pub fn new(result: String, model_id: String) -> DeletedModel {
        DeletedModel {
            result,
            model_id,
        }
    }
}
