/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterStateOverallStats {
    #[serde(rename = "failed_count", default, skip_serializing_if = "Option::is_none")]
    pub failed_count: Option<u32>,
    #[serde(rename = "total_time_in_millis", default, skip_serializing_if = "Option::is_none")]
    pub total_time_in_millis: Option<String>,
    #[serde(rename = "update_count", default, skip_serializing_if = "Option::is_none")]
    pub update_count: Option<u32>,
}

impl ClusterStateOverallStats {
    
    pub fn new() -> ClusterStateOverallStats {
        ClusterStateOverallStats {
            failed_count: None,
            total_time_in_millis: None,
            update_count: None,
        }
    }
}
