/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Http {  /// Current number of open HTTP connections for the node.
    #[serde(rename = "current_open", default, skip_serializing_if = "Option::is_none")]
    pub current_open: Option<u32>,  /// Total number of HTTP connections opened for the node.
    #[serde(rename = "total_opened", default, skip_serializing_if = "Option::is_none")]
    pub total_opened: Option<u32>,
}

impl Http {
    
    pub fn new() -> Http {
        Http {
            current_open: None,
            total_opened: None,
        }
    }
}
