/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use crate::nodes;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ingest {  /// Contains statistics about ingest pipelines for the node.
    #[serde(rename = "pipelines", default, skip_serializing_if = "Option::is_none")]
    pub pipelines: Option<serde_json::Value>,
    #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
    pub total: Option<nodes::stats::IngestTotal>,
}

impl Ingest {
    
    pub fn new() -> Ingest {
        Ingest {
            pipelines: None,
            total: None,
        }
    }
}
