/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JvmClasses {  /// Number of classes currently loaded by JVM.
    #[serde(rename = "current_loaded_count", default, skip_serializing_if = "Option::is_none")]
    pub current_loaded_count: Option<u32>,  /// Total number of classes unloaded since the JVM started.
    #[serde(rename = "total_unloaded_count", default, skip_serializing_if = "Option::is_none")]
    pub total_unloaded_count: Option<u32>,  /// Total number of classes loaded since the JVM started.
    #[serde(rename = "total_loaded_count", default, skip_serializing_if = "Option::is_none")]
    pub total_loaded_count: Option<u32>,
}

impl JvmClasses {
    
    pub fn new() -> JvmClasses {
        JvmClasses {
            current_loaded_count: None,
            total_unloaded_count: None,
            total_loaded_count: None,
        }
    }
}
