/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemoryStatsBase {
    #[serde(rename = "used_in_bytes", default, skip_serializing_if = "Option::is_none")]
    pub used_in_bytes: Option<u32>,
    #[serde(rename = "free_in_bytes", default, skip_serializing_if = "Option::is_none")]
    pub free_in_bytes: Option<u32>,
    #[serde(rename = "total_in_bytes", default, skip_serializing_if = "Option::is_none")]
    pub total_in_bytes: Option<u32>,
    #[serde(rename = "free", default, skip_serializing_if = "Option::is_none")]
    pub free: Option<String>,
    #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
    #[serde(rename = "used", default, skip_serializing_if = "Option::is_none")]
    pub used: Option<String>,
}

impl MemoryStatsBase {
    
    pub fn new() -> MemoryStatsBase {
        MemoryStatsBase {
            used_in_bytes: None,
            free_in_bytes: None,
            total_in_bytes: None,
            free: None,
            total: None,
            used: None,
        }
    }
}
