/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishedClusterStates {  /// Number of published cluster states.
    #[serde(rename = "full_states", default, skip_serializing_if = "Option::is_none")]
    pub full_states: Option<u32>,  /// Number of incompatible differences between published cluster states.
    #[serde(rename = "incompatible_diffs", default, skip_serializing_if = "Option::is_none")]
    pub incompatible_diffs: Option<u32>,  /// Number of compatible differences between published cluster states.
    #[serde(rename = "compatible_diffs", default, skip_serializing_if = "Option::is_none")]
    pub compatible_diffs: Option<u32>,
}

impl PublishedClusterStates {
    
    pub fn new() -> PublishedClusterStates {
        PublishedClusterStates {
            full_states: None,
            incompatible_diffs: None,
            compatible_diffs: None,
        }
    }
}
