/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptStatsBase {  /// Total number of times the script cache has evicted old data.
    #[serde(rename = "cache_evictions")]
    pub cache_evictions: u32,  /// Total number of times the script compilation circuit breaker has limited inline script compilations.
    #[serde(rename = "compilation_limit_triggered")]
    pub compilation_limit_triggered: u32,  /// Total number of inline script compilations performed by the node.
    #[serde(rename = "compilations")]
    pub compilations: u32,
}

impl ScriptStatsBase {
    
    pub fn new(cache_evictions: u32, compilation_limit_triggered: u32, compilations: u32) -> ScriptStatsBase {
        ScriptStatsBase {
            cache_evictions,
            compilation_limit_triggered,
            compilations,
        }
    }
}
