/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardTaskCancellationStatsDetail {
    #[serde(rename = "current_count_post_cancel", default, skip_serializing_if = "Option::is_none")]
    pub current_count_post_cancel: Option<u32>,
    #[serde(rename = "total_count_post_cancel", default, skip_serializing_if = "Option::is_none")]
    pub total_count_post_cancel: Option<u32>,
}

impl ShardTaskCancellationStatsDetail {
    
    pub fn new() -> ShardTaskCancellationStatsDetail {
        ShardTaskCancellationStatsDetail {
            current_count_post_cancel: None,
            total_count_post_cancel: None,
        }
    }
}
