/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::nodes;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardSearchBackpressureStats {
    #[serde(rename = "search_shard_task", default, skip_serializing_if = "Option::is_none")]
    pub search_shard_task: Option<nodes::stats::ShardSearchBackpressureTaskStats>,
    #[serde(rename = "mode", default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<String>,
    #[serde(rename = "search_task", default, skip_serializing_if = "Option::is_none")]
    pub search_task: Option<nodes::stats::ShardSearchBackpressureTaskStats>,
}

impl ShardSearchBackpressureStats {
    
    pub fn new() -> ShardSearchBackpressureStats {
        ShardSearchBackpressureStats {
            search_shard_task: None,
            mode: None,
            search_task: None,
        }
    }
}
