/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardWeightedRoutingStatsDetail {
    #[serde(rename = "fail_open_count", default, skip_serializing_if = "Option::is_none")]
    pub fail_open_count: Option<u32>,
}

impl ShardWeightedRoutingStatsDetail {
    
    pub fn new() -> ShardWeightedRoutingStatsDetail {
        ShardWeightedRoutingStatsDetail {
            fail_open_count: None,
        }
    }
}
