/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardSegmentReplicationBackpressureStats {
    #[serde(rename = "total_rejected_requests", default, skip_serializing_if = "Option::is_none")]
    pub total_rejected_requests: Option<u32>,
}

impl ShardSegmentReplicationBackpressureStats {
    
    pub fn new() -> ShardSegmentReplicationBackpressureStats {
        ShardSegmentReplicationBackpressureStats {
            total_rejected_requests: None,
        }
    }
}
