/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transport {  /// The cumulative number of outbound transport connections that this node has opened since it started.
  /// Each transport connection may comprise multiple TCP connections but is only counted once in this statistic.
  /// Transport connections are typically long-lived so this statistic should remain constant in a stable cluster.
    #[serde(rename = "total_outbound_connections", default, skip_serializing_if = "Option::is_none")]
    pub total_outbound_connections: Option<u32>,  /// Current number of inbound TCP connections used for internal communication between nodes.
    #[serde(rename = "server_open", default, skip_serializing_if = "Option::is_none")]
    pub server_open: Option<u32>,
    #[serde(rename = "rx_size", default, skip_serializing_if = "Option::is_none")]
    pub rx_size: Option<String>,  /// Total number of TX (transmit) packets sent by the node during internal cluster communication.
    #[serde(rename = "tx_count", default, skip_serializing_if = "Option::is_none")]
    pub tx_count: Option<u32>,
    #[serde(rename = "tx_size", default, skip_serializing_if = "Option::is_none")]
    pub tx_size: Option<String>,
    #[serde(rename = "rx_size_in_bytes", default, skip_serializing_if = "Option::is_none")]
    pub rx_size_in_bytes: Option<u32>,
    #[serde(rename = "tx_size_in_bytes", default, skip_serializing_if = "Option::is_none")]
    pub tx_size_in_bytes: Option<u32>,  /// Total number of RX (receive) packets received by the node during internal cluster communication.
    #[serde(rename = "rx_count", default, skip_serializing_if = "Option::is_none")]
    pub rx_count: Option<u32>,
}

impl Transport {
    
    pub fn new() -> Transport {
        Transport {
            total_outbound_connections: None,
            server_open: None,
            rx_size: None,
            tx_count: None,
            tx_size: None,
            rx_size_in_bytes: None,
            tx_size_in_bytes: None,
            rx_count: None,
        }
    }
}
