/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::nodes;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageStats {
    #[serde(rename = "transport", default, skip_serializing_if = "Option::is_none")]
    pub transport: Option<nodes::stats::TransportUsageStats>,
}

impl UsageStats {
    
    pub fn new() -> UsageStats {
        UsageStats {
            transport: None,
        }
    }
}
