/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplicationTaskStatus {
    #[serde(rename = "phase")]
    pub phase: String,
}

impl ReplicationTaskStatus {
    
    pub fn new(phase: String) -> ReplicationTaskStatus {
        ReplicationTaskStatus {
            phase,
        }
    }
}
