/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardPath {
    #[serde(rename = "is_custom_data_path")]
    pub is_custom_data_path: bool,
    #[serde(rename = "data_path")]
    pub data_path: String,
    #[serde(rename = "state_path")]
    pub state_path: String,
}

impl ShardPath {
    pub fn new(is_custom_data_path: bool, data_path: String, state_path: String) -> ShardPath {
        ShardPath {
            is_custom_data_path,
            data_path,
            state_path,
        }
    }
}
