/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShardCommit {
    #[serde(rename = "user_data")]
    pub user_data: serde_json::Value,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "num_docs")]
    pub num_docs: u32,
    #[serde(rename = "generation")]
    pub generation: u32,
}

impl ShardCommit {
    pub fn new(
        user_data: serde_json::Value,
        id: String,
        num_docs: u32,
        generation: u32,
    ) -> ShardCommit {
        ShardCommit {
            user_data,
            id,
            num_docs,
            generation,
        }
    }
}
