/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

pub mod multi_search_result;
pub use self::multi_search_result::MultiSearchResult;

pub mod multisearch_body;
pub use self::multisearch_body::MultisearchBody;

pub mod multisearch_header;
pub use self::multisearch_header::MultisearchHeader;

pub mod request_item;
pub use self::request_item::RequestItem;

pub mod response_item;
pub use self::response_item::ResponseItem;
