/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::snapshot;
use serde::{Deserialize, Serialize};

/// CreateRepository
/// The repository definition


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRepository {
    #[serde(rename = "repository", default, skip_serializing_if = "Option::is_none")]
    pub repository: Option<snapshot::Repository>,
    #[serde(rename = "settings")]
    pub settings: snapshot::RepositorySettings,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CreateRepository {
      /// The repository definition
    pub fn new(settings: snapshot::RepositorySettings, r#type: String) -> CreateRepository {
        CreateRepository {
            repository: None,
            settings,
            r#type,
        }
    }
}
