/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotShardsStats {
    #[serde(rename = "initializing")]
    pub initializing: u32,
    #[serde(rename = "finalizing")]
    pub finalizing: u32,
    #[serde(rename = "failed")]
    pub failed: u32,
    #[serde(rename = "done")]
    pub done: u32,
    #[serde(rename = "total")]
    pub total: u32,
    #[serde(rename = "started")]
    pub started: u32,
}

impl SnapshotShardsStats {
    
    pub fn new(initializing: u32, finalizing: u32, failed: u32, done: u32, total: u32, started: u32) -> SnapshotShardsStats {
        SnapshotShardsStats {
            initializing,
            finalizing,
            failed,
            done,
            total,
            started,
        }
    }
}
