/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::snapshot;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponse {
    #[serde(rename = "snapshots")]
    pub snapshots: Vec<snapshot::SnapshotStatus>,
}

impl StatusResponse {
    
    pub fn new(snapshots: Vec<snapshot::SnapshotStatus>) -> StatusResponse {
        StatusResponse {
            snapshots,
        }
    }
}
