/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyRepositoryResponse {
    #[serde(rename = "nodes")]
    pub nodes: serde_json::Value,
}

impl VerifyRepositoryResponse {
    
    pub fn new(nodes: serde_json::Value) -> VerifyRepositoryResponse {
        VerifyRepositoryResponse {
            nodes,
        }
    }
}
