[package]
name = "opensearch-client"
description = "Strongly typed OpenSearch Client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
readme = "README.md"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
base64 = { workspace = true }
bon = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
http = { workspace = true }
# client stuff
# task-local-extensions = "0.1.4"
loco-rs = { workspace = true, optional = true }

opensearch-dsl = { workspace = true, optional = true }
opensearch-macro = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
reqwest-middleware = { workspace = true, features = [
    "json",
    "multipart",
    "query",
] }
reqwest-retry = { workspace = true }
reqwest-tracing = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true, features = ["base64", "std", "macros"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true, optional = true }

[dev-dependencies]
opensearch-testcontainer = { workspace = true }
testcontainers = { workspace = true }
tracing-test = { workspace = true }

[features]
default = ["bon", "search", "indices", "ingest", "cluster", "ml"]
bon = ["dep:bon"]

full = [
    "search",              # search features
    "asynchronous_search", # asynchronous search features
    "cat",
    "cluster",
    "dangling_indices",
    "indices",
    "ingest",
    "insights",
    "ism",
    "knn",
    "ml",
    "nodes",
    "notifications",
    "observability",
    "ppl",
    "remote_store",
    "replication",
    "rollups",
    "security",
    "snapshot",
    "sql",
    "tasks",
    "transforms",
    "tools",
]

quickwit = []
# loco RS error mangement 
loco = ["dep:loco-rs", "dep:axum"]
search = ["dep:opensearch-dsl", "dep:futures"]
asynchronous_search = []
cat = []
cluster = []
dangling_indices = []
indices = ["search"]
ingest = []
insights = []
ism = []
knn = []
ml = []
nodes = []
notifications = []
observability = []
ppl = []
remote_store = []
replication = []
rollups = []
security = []
snapshot = []
sql = []
tasks = []
transforms = []
# custom features
tools = ["indices", "ingest", "dep:walkdir", "ml", "dep:futures"]
