/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

mod document;
pub use self::document::Document;

mod document_simulation;
pub use self::document_simulation::DocumentSimulation;

mod ingest;
pub use self::ingest::Ingest;

mod pipeline_simulation;
pub use self::pipeline_simulation::PipelineSimulation;
mod simulate;
pub use self::simulate::Simulate;
