/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteStoreRestoreShardsInfo {
    #[serde(rename = "failed", default, skip_serializing_if = "Option::is_none")]
    pub failed: Option<u32>,
    #[serde(rename = "successful", default, skip_serializing_if = "Option::is_none")]
    pub successful: Option<u32>,
    #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
    pub total: Option<u32>,
}

impl RemoteStoreRestoreShardsInfo {
    
    pub fn new() -> RemoteStoreRestoreShardsInfo {
        RemoteStoreRestoreShardsInfo {
            failed: None,
            successful: None,
            total: None,
        }
    }
}
