/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::remote_store;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestoreResponse {
    #[serde(rename = "accepted", default, skip_serializing_if = "Option::is_none")]
    pub accepted: Option<bool>,
    #[serde(rename = "remote_store", default, skip_serializing_if = "Option::is_none")]
    pub remote_store: Option<remote_store::RemoteStoreRestoreInfo>,
}

impl RestoreResponse {
    
    pub fn new() -> RestoreResponse {
        RestoreResponse {
            accepted: None,
            remote_store: None,
        }
    }
}
