/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArrayPercentilesItem {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value_as_string", default, skip_serializing_if = "Option::is_none")]
    pub value_as_string: Option<String>,
}

impl ArrayPercentilesItem {
    
    pub fn new(key: String) -> ArrayPercentilesItem {
        ArrayPercentilesItem {
            key,
            value_as_string: None,
        }
    }
}
