/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConditionTokenFilter {
    #[serde(rename = "filter", default, skip_serializing_if = "Vec::is_empty")]
    pub filter: Vec<String>,
    #[serde(rename = "script")]
    pub script: serde_json::Value,
}

impl ConditionTokenFilter {
    pub fn new(filter: Vec<String>, script: serde_json::Value) -> Self {
        Self { filter, script }
    }
}
