/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct EdgeNGramTokenFilter {
    #[serde(rename = "min_gram", default, skip_serializing_if = "Option::is_none")]
    pub min_gram: Option<u32>,
    #[serde(rename = "max_gram", default, skip_serializing_if = "Option::is_none")]
    pub max_gram: Option<u32>,
    #[serde(
        rename = "preserve_original",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub preserve_original: Option<bool>,
}

impl EdgeNGramTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
