/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IcuTransformTokenFilter {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "dir", default, skip_serializing_if = "Option::is_none")]
    pub dir: Option<String>,
}

impl IcuTransformTokenFilter {
    pub fn new(id: String) -> Self {
        Self { id, dir: None }
    }
}
