/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IcuAnalyzer {
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl IcuAnalyzer {
    
    pub fn new(method: String, mode: String, r#type: String) -> IcuAnalyzer {
        IcuAnalyzer {
            method,
            mode,
            r#type,
        }
    }
}
