/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct KeywordMarkerTokenFilter {
    #[serde(rename = "keywords", default, skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<String>>,
    #[serde(
        rename = "keywords_path",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub keywords_path: Option<String>,
    #[serde(
        rename = "keywords_pattern",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub keywords_pattern: Option<String>,
    #[serde(
        rename = "ignore_case",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_case: Option<bool>,
}

impl KeywordMarkerTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
