/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct KuromojiPartOfSpeechTokenFilter {
    #[serde(rename = "stoptags", default, skip_serializing_if = "Option::is_none")]
    pub stoptags: Option<Vec<String>>,
}

impl KuromojiPartOfSpeechTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
