/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct LimitTokenFilter {
    #[serde(
        rename = "max_token_count",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_token_count: Option<u32>,
    #[serde(
        rename = "consume_all_tokens",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub consume_all_tokens: Option<bool>,
}

impl LimitTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
