/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct MappingCharFilter {
    #[serde(rename = "mappings", default, skip_serializing_if = "Option::is_none")]
    pub mappings: Option<Vec<String>>,
    #[serde(
        rename = "mappings_path",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub mappings_path: Option<String>,
}

impl MappingCharFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
