/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatternReplaceCharFilter {
    #[serde(rename = "pattern")]
    pub pattern: String,
    #[serde(
        rename = "replacement",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub replacement: Option<String>,
}

impl PatternReplaceCharFilter {
    pub fn new(pattern: String) -> Self {
        Self {
            pattern,
            replacement: None,
        }
    }
}
