/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhoneAnalyzer {  /// Optional ISO 3166 country code, defaults to "ZZ" (unknown region).
    #[serde(rename = "phone-region", default, skip_serializing_if = "Option::is_none")]
    pub phone_region: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl PhoneAnalyzer {
    
    pub fn new() -> PhoneAnalyzer {
        PhoneAnalyzer {
            phone_region: None,
            r#type: None,
        }
    }
}
