/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct PhoneticTokenFilter {
    #[serde(rename = "encoder", default, skip_serializing_if = "Option::is_none")]
    pub encoder: Option<String>,
    #[serde(rename = "replace", default, skip_serializing_if = "Option::is_none")]
    pub replace: Option<bool>,
}

impl PhoneticTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
