/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnowballTokenFilter {
    #[serde(rename = "language")]
    pub language: String,
}

impl SnowballTokenFilter {
    pub fn new(language: String) -> Self {
        Self { language }
    }
}
