/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnowballAnalyzer {
    #[serde(rename = "stopwords", default, skip_serializing_if = "Option::is_none")]
    pub stopwords: Option<common::analysis::StopWords>,
    #[serde(rename = "version", default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SnowballAnalyzer {
    
    pub fn new(language: String, r#type: String) -> SnowballAnalyzer {
        SnowballAnalyzer {
            stopwords: None,
            version: None,
            language,
            r#type,
        }
    }
}
