/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

use crate::common::analysis::StopWords;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct StopTokenFilter {
    #[serde(rename = "stopwords", default, skip_serializing_if = "Option::is_none")]
    pub stopwords: Option<StopWords>,
    #[serde(
        rename = "stopwords_path",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stopwords_path: Option<String>,
    #[serde(
        rename = "ignore_case",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_case: Option<bool>,
    #[serde(
        rename = "remove_trailing",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub remove_trailing: Option<bool>,
}

impl StopTokenFilter {
    pub fn new() -> Self {
        Self::default()
    }
}
