/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

use super::{
    CharGroupTokenizer, EdgeNGramTokenizer, IcuTokenizer, KeywordTokenizer, KuromojiTokenizer,
    NGramTokenizer, NoriTokenizer, PathHierarchyTokenizer, PatternTokenizer,
    SimplePatternSplitTokenizer, SimplePatternTokenizer, StandardTokenizer, UaxUrlEmailTokenizer,
    WhitespaceTokenizer,
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TokenizerDefinition {
    #[serde(rename = "standard")]
    Standard(StandardTokenizer),
    #[serde(rename = "ngram")]
    NGram(NGramTokenizer),
    #[serde(rename = "edge_ngram")]
    EdgeNGram(EdgeNGramTokenizer),
    #[serde(rename = "keyword")]
    Keyword(KeywordTokenizer),
    #[serde(rename = "pattern")]
    Pattern(PatternTokenizer),
    #[serde(rename = "whitespace")]
    Whitespace(WhitespaceTokenizer),
    #[serde(rename = "uax_url_email")]
    UaxUrlEmail(UaxUrlEmailTokenizer),
    #[serde(rename = "path_hierarchy")]
    PathHierarchy(PathHierarchyTokenizer),
    #[serde(rename = "char_group")]
    CharGroup(CharGroupTokenizer),
    #[serde(rename = "simple_pattern")]
    SimplePattern(SimplePatternTokenizer),
    #[serde(rename = "simple_pattern_split")]
    SimplePatternSplit(SimplePatternSplitTokenizer),
    #[serde(rename = "letter")]
    Letter,
    #[serde(rename = "lowercase")]
    Lowercase,
    #[serde(rename = "thai")]
    Thai,
    #[serde(rename = "classic")]
    Classic,
    // Plugin tokenizers
    #[serde(rename = "icu_tokenizer")]
    Icu(IcuTokenizer),
    #[serde(rename = "kuromoji_tokenizer")]
    Kuromoji(KuromojiTokenizer),
    #[serde(rename = "nori_tokenizer")]
    Nori(NoriTokenizer),
    #[serde(rename = "smartcn_tokenizer")]
    Smartcn,
}

#[cfg(test)]
mod tests {
    use serde_json::{from_str, to_string};

    use super::*;

    #[test]
    fn test_letter_unit_variant() {
        let json = r#"{"type":"letter"}"#;
        let d: TokenizerDefinition = from_str(json).unwrap();
        assert_eq!(d, TokenizerDefinition::Letter);
        assert_eq!(to_string(&d).unwrap(), json);
    }

    #[test]
    fn test_ngram_tokenizer() {
        let json = r#"{"type":"ngram","min_gram":2,"max_gram":3}"#;
        let d: TokenizerDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenizerDefinition::NGram(_)));
    }

    #[test]
    fn test_standard_tokenizer() {
        let json = r#"{"type":"standard"}"#;
        let d: TokenizerDefinition = from_str(json).unwrap();
        assert_eq!(
            d,
            TokenizerDefinition::Standard(StandardTokenizer::default())
        );
    }
}
