/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use serde::{Deserialize, Serialize};

use super::{
    AsciiFoldingTokenFilter, CjkBigramTokenFilter, CommonGramsTokenFilter, ConditionTokenFilter,
    DelimitedPayloadTokenFilter, DelimitedTermFreqTokenFilter, DictionaryDecompounderTokenFilter,
    EdgeNGramTokenFilter, ElisionTokenFilter, FingerprintTokenFilter, HunspellTokenFilter,
    HyphenationDecompounderTokenFilter, IcuCollationTokenFilter, IcuFoldingTokenFilter,
    IcuNormalizerTokenFilter, IcuTransformTokenFilter, JaStopTokenFilter, KeepTypesTokenFilter,
    KeepWordsTokenFilter, KeywordMarkerTokenFilter, KuromojiCompletionTokenFilter,
    KuromojiPartOfSpeechTokenFilter, KuromojiReadingFormTokenFilter, KuromojiStemmerTokenFilter,
    LengthTokenFilter, LimitTokenFilter, LowercaseTokenFilter, MinHashTokenFilter,
    MultiplexerTokenFilter, NGramTokenFilter, NoriPartOfSpeechTokenFilter,
    PatternCaptureTokenFilter, PatternReplaceTokenFilter, PersianStemTokenFilter,
    PhoneticTokenFilter, PredicateTokenFilter, ShingleTokenFilter, SnowballTokenFilter,
    StemmerOverrideTokenFilter, StemmerTokenFilter, StopTokenFilter, SynonymGraphTokenFilter,
    SynonymTokenFilter, TruncateTokenFilter, UniqueTokenFilter, WordDelimiterGraphTokenFilter,
    WordDelimiterTokenFilter,
};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TokenFilterDefinition {
    // Unit variants — no configurable parameters
    #[serde(rename = "apostrophe")]
    Apostrophe,
    #[serde(rename = "cjk_width")]
    CjkWidth,
    #[serde(rename = "classic")]
    Classic,
    #[serde(rename = "decimal_digit")]
    DecimalDigit,
    #[serde(rename = "flatten_graph")]
    FlattenGraph,
    #[serde(rename = "keyword_repeat")]
    KeywordRepeat,
    #[serde(rename = "kstem")]
    KStem,
    #[serde(rename = "porter_stem")]
    PorterStem,
    #[serde(rename = "remove_duplicates")]
    RemoveDuplicates,
    #[serde(rename = "reverse")]
    Reverse,
    #[serde(rename = "trim")]
    Trim,
    #[serde(rename = "uppercase")]
    Uppercase,
    // Normalization unit variants
    #[serde(rename = "arabic_normalization")]
    ArabicNormalization,
    #[serde(rename = "german_normalization")]
    GermanNormalization,
    #[serde(rename = "hindi_normalization")]
    HindiNormalization,
    #[serde(rename = "indic_normalization")]
    IndicNormalization,
    #[serde(rename = "sorani_normalization")]
    SoraniNormalization,
    #[serde(rename = "persian_normalization")]
    PersianNormalization,
    #[serde(rename = "scandinavian_normalization")]
    ScandinavianNormalization,
    #[serde(rename = "scandinavian_folding")]
    ScandinavianFolding,
    #[serde(rename = "serbian_normalization")]
    SerbianNormalization,
    #[serde(rename = "bengali_normalization")]
    BengaliNormalization,
    // Parametric standard filters
    #[serde(rename = "asciifolding")]
    AsciiFolding(AsciiFoldingTokenFilter),
    #[serde(rename = "cjk_bigram")]
    CjkBigram(CjkBigramTokenFilter),
    #[serde(rename = "common_grams")]
    CommonGrams(CommonGramsTokenFilter),
    #[serde(rename = "condition")]
    Condition(ConditionTokenFilter),
    #[serde(rename = "delimited_payload")]
    DelimitedPayload(DelimitedPayloadTokenFilter),
    #[serde(rename = "delimited_term_freq")]
    DelimitedTermFreq(DelimitedTermFreqTokenFilter),
    #[serde(rename = "dictionary_decompounder")]
    DictionaryDecompounder(DictionaryDecompounderTokenFilter),
    #[serde(rename = "edge_ngram")]
    EdgeNGram(EdgeNGramTokenFilter),
    #[serde(rename = "elision")]
    Elision(ElisionTokenFilter),
    #[serde(rename = "fingerprint")]
    Fingerprint(FingerprintTokenFilter),
    #[serde(rename = "keep_types")]
    KeepTypes(KeepTypesTokenFilter),
    #[serde(rename = "keep")]
    Keep(KeepWordsTokenFilter),
    #[serde(rename = "keyword_marker")]
    KeywordMarker(KeywordMarkerTokenFilter),
    #[serde(rename = "length")]
    Length(LengthTokenFilter),
    #[serde(rename = "limit")]
    Limit(LimitTokenFilter),
    #[serde(rename = "lowercase")]
    Lowercase(LowercaseTokenFilter),
    #[serde(rename = "min_hash")]
    MinHash(MinHashTokenFilter),
    #[serde(rename = "multiplexer")]
    Multiplexer(MultiplexerTokenFilter),
    #[serde(rename = "ngram")]
    NGram(NGramTokenFilter),
    #[serde(rename = "pattern_capture")]
    PatternCapture(PatternCaptureTokenFilter),
    #[serde(rename = "pattern_replace")]
    PatternReplace(PatternReplaceTokenFilter),
    #[serde(rename = "shingle")]
    Shingle(ShingleTokenFilter),
    #[serde(rename = "snowball")]
    Snowball(SnowballTokenFilter),
    #[serde(rename = "stemmer")]
    Stemmer(StemmerTokenFilter),
    #[serde(rename = "stemmer_override")]
    StemmerOverride(StemmerOverrideTokenFilter),
    #[serde(rename = "stop")]
    Stop(StopTokenFilter),
    #[serde(rename = "synonym")]
    Synonym(SynonymTokenFilter),
    #[serde(rename = "synonym_graph")]
    SynonymGraph(SynonymGraphTokenFilter),
    #[serde(rename = "truncate")]
    Truncate(TruncateTokenFilter),
    #[serde(rename = "unique")]
    Unique(UniqueTokenFilter),
    #[serde(rename = "word_delimiter")]
    WordDelimiter(WordDelimiterTokenFilter),
    #[serde(rename = "word_delimiter_graph")]
    WordDelimiterGraph(WordDelimiterGraphTokenFilter),
    // Plugin filters
    #[serde(rename = "hunspell")]
    Hunspell(HunspellTokenFilter),
    #[serde(rename = "hyphenation_decompounder")]
    HyphenationDecompounder(HyphenationDecompounderTokenFilter),
    #[serde(rename = "icu_folding")]
    IcuFolding(IcuFoldingTokenFilter),
    #[serde(rename = "icu_normalizer")]
    IcuNormalizer(IcuNormalizerTokenFilter),
    #[serde(rename = "icu_transform")]
    IcuTransform(IcuTransformTokenFilter),
    #[serde(rename = "icu_collation")]
    IcuCollation(IcuCollationTokenFilter),
    #[serde(rename = "ja_stop")]
    JaStop(JaStopTokenFilter),
    #[serde(rename = "kuromoji_baseform")]
    KuromojiBaseform,
    #[serde(rename = "kuromoji_completion")]
    KuromojiCompletion(KuromojiCompletionTokenFilter),
    #[serde(rename = "kuromoji_number")]
    KuromojiNumber,
    #[serde(rename = "kuromoji_part_of_speech")]
    KuromojiPartOfSpeech(KuromojiPartOfSpeechTokenFilter),
    #[serde(rename = "kuromoji_readingform")]
    KuromojiReadingForm(KuromojiReadingFormTokenFilter),
    #[serde(rename = "kuromoji_stemmer")]
    KuromojiStemmer(KuromojiStemmerTokenFilter),
    #[serde(rename = "nori_part_of_speech")]
    NoriPartOfSpeech(NoriPartOfSpeechTokenFilter),
    #[serde(rename = "polish_stop")]
    PolishStop,
    #[serde(rename = "polish_stem")]
    PolishStem,
    #[serde(rename = "phonetic")]
    Phonetic(PhoneticTokenFilter),
    #[serde(rename = "predicate_token_filter")]
    Predicate(PredicateTokenFilter),
    #[serde(rename = "persian_stem")]
    PersianStem(PersianStemTokenFilter),
    #[serde(rename = "smartcn_stop")]
    SmartcnStop,
}

#[cfg(test)]
mod tests {
    use serde_json::{from_str, to_string};

    use super::*;

    #[test]
    fn test_reverse_unit_variant() {
        let json = r#"{"type":"reverse"}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert_eq!(d, TokenFilterDefinition::Reverse);
        assert_eq!(to_string(&d).unwrap(), json);
    }

    #[test]
    fn test_apostrophe_unit_variant() {
        let json = r#"{"type":"apostrophe"}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert_eq!(d, TokenFilterDefinition::Apostrophe);
    }

    #[test]
    fn test_arabic_normalization() {
        let json = r#"{"type":"arabic_normalization"}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert_eq!(d, TokenFilterDefinition::ArabicNormalization);
        assert_eq!(to_string(&d).unwrap(), json);
    }

    #[test]
    fn test_stop_with_stopwords() {
        let json = r#"{"type":"stop","ignore_case":true}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenFilterDefinition::Stop(_)));
        let back = to_string(&d).unwrap();
        let d2: TokenFilterDefinition = from_str(&back).unwrap();
        assert_eq!(d, d2);
    }

    #[test]
    fn test_stop_minimal() {
        let json = r#"{"type":"stop"}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenFilterDefinition::Stop(_)));
    }

    #[test]
    fn test_synonym() {
        let json = r#"{"type":"synonym","synonyms":["i-pod, i pod => ipod"]}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenFilterDefinition::Synonym(_)));
    }

    #[test]
    fn test_shingle() {
        let json = r#"{"type":"shingle","min_shingle_size":2,"max_shingle_size":3}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenFilterDefinition::Shingle(_)));
    }

    #[test]
    fn test_word_delimiter_graph() {
        let json =
            r#"{"type":"word_delimiter_graph","preserve_original":true,"adjust_offsets":false}"#;
        let d: TokenFilterDefinition = from_str(json).unwrap();
        assert!(matches!(d, TokenFilterDefinition::WordDelimiterGraph(_)));
    }
}
