/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::notifications;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConfig {
    #[serde(rename = "config")]
    pub config: notifications::NotificationsConfigItem,
    #[serde(rename = "config_id", default, skip_serializing_if = "Option::is_none")]
    pub config_id: Option<String>,
}

impl CreateConfig {
    
    pub fn new(config: notifications::NotificationsConfigItem) -> CreateConfig {
        CreateConfig {
            config,
            config_id: None,
        }
    }
}
