/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::notifications;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Email {
    #[serde(rename = "email_account_id")]
    pub email_account_id: String,
    #[serde(rename = "recipient_list", default, skip_serializing_if = "Option::is_none")]
    pub recipient_list: Option<Vec<notifications::RecipientListItem>>,
}

impl Email {
    
    pub fn new(email_account_id: String) -> Email {
        Email {
            email_account_id,
            recipient_list: None,
        }
    }
}
