/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SesAccount {
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "role_arn", default, skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
    #[serde(rename = "from_address")]
    pub from_address: String,
}

impl SesAccount {
    
    pub fn new(region: String, from_address: String) -> SesAccount {
        SesAccount {
            region,
            role_arn: None,
            from_address,
        }
    }
}
