/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::dangling_indices;
use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDanglingIndicesResponse {
    #[serde(rename = "dangling_indices")]
    pub dangling_indices: Vec<dangling_indices::list_dangling_indices::DanglingIndex>,
    #[serde(rename = "cluster_name", default, skip_serializing_if = "Option::is_none")]
    pub cluster_name: Option<String>,
    #[serde(rename = "_nodes", default, skip_serializing_if = "Option::is_none")]
    pub nodes: Option<common::NodeStatistics>,
}

impl ListDanglingIndicesResponse {
    
    pub fn new(dangling_indices: Vec<dangling_indices::list_dangling_indices::DanglingIndex>) -> ListDanglingIndicesResponse {
        ListDanglingIndicesResponse {
            dangling_indices,
            cluster_name: None,
            nodes: None,
        }
    }
}
