/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

pub mod list_dangling_indices_response;
pub use self::list_dangling_indices_response::ListDanglingIndicesResponse;
