/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

mod action;
pub use self::action::Action;

mod add_action;
pub use self::add_action::AddAction;

mod remove_action;
pub use self::remove_action::RemoveAction;

mod remove_index_action;
pub use remove_index_action::RemoveIndexAction;
mod update_aliases;
pub use update_aliases::UpdateAliases;
