/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::core;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HitsMetadata {
    #[serde(rename = "hits")]
    pub hits: Vec<core::search::Hit>,
}

impl HitsMetadata {
    
    pub fn new(hits: Vec<core::search::Hit>) -> HitsMetadata {
        HitsMetadata {
            hits,
        }
    }
}
