/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinearInterpolationSmoothingModel {
    #[serde(rename = "trigram_lambda")]
    pub trigram_lambda: f64,
    #[serde(rename = "bigram_lambda")]
    pub bigram_lambda: f64,
    #[serde(rename = "unigram_lambda")]
    pub unigram_lambda: f64,
}

impl LinearInterpolationSmoothingModel {
    
    pub fn new(trigram_lambda: f64, bigram_lambda: f64, unigram_lambda: f64) -> LinearInterpolationSmoothingModel {
        LinearInterpolationSmoothingModel {
            trigram_lambda,
            bigram_lambda,
            unigram_lambda,
        }
    }
}
