/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::core;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalHits {
    #[serde(rename = "relation")]
    pub relation: String,
    #[serde(rename = "value")]
    pub value: u32,
}

impl TotalHits {
    
    pub fn new(relation: String, value: u32) -> TotalHits {
        TotalHits {
            relation,
            value,
        }
    }
}
