/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldStatistics {
    #[serde(rename = "sum_ttf")]
    pub sum_ttf: u32,
    #[serde(rename = "sum_doc_freq")]
    pub sum_doc_freq: u32,
    #[serde(rename = "doc_count")]
    pub doc_count: u32,
}

impl FieldStatistics {
    
    pub fn new(sum_ttf: u32, sum_doc_freq: u32, doc_count: u32) -> FieldStatistics {
        FieldStatistics {
            sum_ttf,
            sum_doc_freq,
            doc_count,
        }
    }
}
