/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoFollowStats {
    #[serde(rename = "last_execution_time", default, skip_serializing_if = "Option::is_none")]
    pub last_execution_time: Option<f64>,
    #[serde(rename = "num_failed_leader_calls", default, skip_serializing_if = "Option::is_none")]
    pub num_failed_leader_calls: Option<f64>,
    #[serde(rename = "pattern", default, skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "num_failed_start_replication", default, skip_serializing_if = "Option::is_none")]
    pub num_failed_start_replication: Option<f64>,
    #[serde(rename = "num_success_start_replication", default, skip_serializing_if = "Option::is_none")]
    pub num_success_start_replication: Option<f64>,
    #[serde(rename = "failed_indices", default, skip_serializing_if = "Option::is_none")]
    pub failed_indices: Option<Vec<String>>,
}

impl AutoFollowStats {
    
    pub fn new() -> AutoFollowStats {
        AutoFollowStats {
            last_execution_time: None,
            num_failed_leader_calls: None,
            pattern: None,
            name: None,
            num_failed_start_replication: None,
            num_success_start_replication: None,
            failed_indices: None,
        }
    }
}
