/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteReplicationRule {
    #[serde(rename = "leader_alias", default, skip_serializing_if = "Option::is_none")]
    pub leader_alias: Option<String>,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl DeleteReplicationRule {
    
    pub fn new() -> DeleteReplicationRule {
        DeleteReplicationRule {
            leader_alias: None,
            name: None,
        }
    }
}
