/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSchema {
    #[serde(rename = "number_of_replicas", default, skip_serializing_if = "Option::is_none")]
    pub number_of_replicas: Option<u32>,
    #[serde(rename = "number_of_shards", default, skip_serializing_if = "Option::is_none")]
    pub number_of_shards: Option<u32>,
}

impl IndexSchema {
    
    pub fn new() -> IndexSchema {
        IndexSchema {
            number_of_replicas: None,
            number_of_shards: None,
        }
    }
}
