/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::rollups;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Put {
    #[serde(rename = "_primary_term", default, skip_serializing_if = "Option::is_none")]
    pub primary_term: Option<u32>,
    #[serde(rename = "rollup", default, skip_serializing_if = "Option::is_none")]
    pub rollup: Option<rollups::Rollup>,
    #[serde(rename = "_version", default, skip_serializing_if = "Option::is_none")]
    pub version: Option<u32>,
    #[serde(rename = "_id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "_seq_no", default, skip_serializing_if = "Option::is_none")]
    pub seq_no: Option<u32>,
}

impl Put {
    
    pub fn new() -> Put {
        Put {
            primary_term: None,
            rollup: None,
            version: None,
            id: None,
            seq_no: None,
        }
    }
}
