/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcknowledgedResponseBase {  /// For a successful response, this value is always true. On failure, an exception is returned instead.
    #[serde(rename = "acknowledged")]
    pub acknowledged: bool,
}

impl AcknowledgedResponseBase {
    
    pub fn new(acknowledged: bool) -> AcknowledgedResponseBase {
        AcknowledgedResponseBase {
            acknowledged,
        }
    }
}
