/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use crate::common;
use crate::common::ScrollableHitSourceSearchFailure;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum BulkByScrollFailure {
    ScrollableHitSourceSearchFailureValue(ScrollableHitSourceSearchFailure),

    BulkItemResponseFailureValue(crate::bulk::BulkItemResponse),
}
