/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

/// ClearScrollRequestBodyJson
/// Comma-separated list of scroll IDs to clear if none was specified using the `scroll_id` parameter


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClearScrollRequestBodyJson {
    #[serde(rename = "scroll_id", default, skip_serializing_if = "Option::is_none")]
    pub scroll_id: Option<common::ScrollIds>,
}

impl ClearScrollRequestBodyJson {
      /// Comma-separated list of scroll IDs to clear if none was specified using the `scroll_id` parameter
    pub fn new() -> ClearScrollRequestBodyJson {
        ClearScrollRequestBodyJson {
            scroll_id: None,
        }
    }
}
