/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClearScrollNotFoundJson {
    #[serde(rename = "num_freed")]
    pub num_freed: u32,
    #[serde(rename = "succeeded")]
    pub succeeded: bool,
}

impl ClearScrollNotFoundJson {
    
    pub fn new(num_freed: u32, succeeded: bool) -> ClearScrollNotFoundJson {
        ClearScrollNotFoundJson {
            num_freed,
            succeeded,
        }
    }
}
