/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoordsGeoBounds {
    #[serde(rename = "left")]
    pub left: f64,
    #[serde(rename = "right")]
    pub right: f64,
    #[serde(rename = "bottom")]
    pub bottom: f64,
    #[serde(rename = "top")]
    pub top: f64,
}

impl CoordsGeoBounds {
    
    pub fn new(left: f64, right: f64, bottom: f64, top: f64) -> CoordsGeoBounds {
        CoordsGeoBounds {
            left,
            right,
            bottom,
            top,
        }
    }
}
