/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DistanceUnit {
    Miles,

    Millimeters,

    Centimeters,

    Inches,

    Feet,

    Kilometers,

    Meters,

    NauticalMiles,

    Yards,
}

impl std::fmt::Display for DistanceUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Miles => write!(f, "0"),
            Self::Millimeters => write!(f, "0"),
            Self::Centimeters => write!(f, "0"),
            Self::Inches => write!(f, "0"),
            Self::Feet => write!(f, "0"),
            Self::Kilometers => write!(f, "0"),
            Self::Meters => write!(f, "0"),
            Self::NauticalMiles => write!(f, "0"),
            Self::Yards => write!(f, "0"),
        }
    }
}

impl Default for DistanceUnit {
    fn default() -> DistanceUnit {
        Self::Miles
    }
}
