/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use crate::common;
use crate::common::Sort;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Hash, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FieldSort {
    SortOrderValue(common::SortOptionsValue),

    ObjectValue(serde_json::Value),
}
