/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldMemoryUsage {
    #[serde(rename = "memory_size", default, skip_serializing_if = "Option::is_none")]
    pub memory_size: Option<String>,
    #[serde(rename = "memory_size_in_bytes")]
    pub memory_size_in_bytes: u32,
}

impl FieldMemoryUsage {
    
    pub fn new(memory_size_in_bytes: u32) -> FieldMemoryUsage {
        FieldMemoryUsage {
            memory_size: None,
            memory_size_in_bytes,
        }
    }
}
