/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

/// full_id

/// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
/// this behavior while keeping the semantics of the field type.
///
/// Depending on the target language, code generators can keep the union or remove it and leniently parse
/// strings to the target type.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum FullId {
    StringValue(String),

    BooleanValue(bool),
}
