/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct GeoHashLocation {
    #[serde(rename = "geohash")]
    pub geohash: String,
}

impl GeoHashLocation {
    pub fn new(geohash: String) -> GeoHashLocation {
        GeoHashLocation { geohash }
    }
}
