/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

/// GeoBounds

/// A geo-bounding box. It can be represented in the following ways:
/// - As 4 top/bottom/left/right coordinates.
/// - As 2 top_left/bottom_right points.
/// - As 2 top_right/bottom_left points.
/// - As a Well Known Text (WKT) bounding box.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GeoBounds {
    CoordsGeoBounds,
    WktGeoBoundsValue,
    TopLeftBottomRightGeoBoundsValue,
    TopRightBottomLeftGeoBoundsValue,
}
