/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

/// GeoHashPrecision
/// The level of geohash precision, which can be expressed as a geohash length between 1 and 12 or as a distance measure, such as "1km" or "10m".

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GeoHashPrecision {
    GeohashLengthValue(u32),
    DistanceValue(String),
}
