/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::core;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetScriptContextResponse {
    #[serde(rename = "contexts")]
    pub contexts: Vec<core::get_script_context::Context>,
}

impl GetScriptContextResponse {
    
    pub fn new(contexts: Vec<core::get_script_context::Context>) -> GetScriptContextResponse {
        GetScriptContextResponse {
            contexts,
        }
    }
}
