/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoResponse {
    #[serde(rename = "cluster_name")]
    pub cluster_name: String,
    #[serde(rename = "tagline")]
    pub tagline: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "cluster_uuid")]
    pub cluster_uuid: String,
    #[serde(rename = "version")]
    pub version: common::OpenSearchVersionInfo,
}

impl InfoResponse {
    
    pub fn new(cluster_name: String, tagline: String, name: String, cluster_uuid: String, version: common::OpenSearchVersionInfo) -> InfoResponse {
        InfoResponse {
            cluster_name,
            tagline,
            name,
            cluster_uuid,
            version,
        }
    }
}
