/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineScript {
    pub source: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<common::ScriptLanguage>,
    /// The script source.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
}

impl InlineScript {
    pub fn new(script: &str) -> InlineScript {
        InlineScript {
            source: script.to_string(),
            lang: None,
            params: None,
        }
    }
}
