/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

/// PutScript
/// The document


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutScript {
    #[serde(rename = "script")]
    pub script: common::StoredScript,
}

impl PutScript {
      /// The document
    pub fn new(script: common::StoredScript) -> PutScript {
        PutScript {
            script,
        }
    }
}
