/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use crate::core;
use serde::{Deserialize, Serialize};

/// Reindex
/// The search definition using the Query DSL and the prototype for the index request.


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reindex {
    #[serde(rename = "dest")]
    pub dest: core::reindex::Destination,
    #[serde(rename = "conflicts", default, skip_serializing_if = "Option::is_none")]
    pub conflicts: Option<String>,  /// The maximum number of documents to reindex.
    #[serde(rename = "max_docs", default, skip_serializing_if = "Option::is_none")]
    pub max_docs: Option<u32>,
    #[serde(rename = "script", default, skip_serializing_if = "Option::is_none")]
    pub script: Option<common::Script>,
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<u32>,
    #[serde(rename = "source")]
    pub source: core::reindex::Source,
}

impl Reindex {
      /// The search definition using the Query DSL and the prototype for the index request.
    pub fn new(dest: core::reindex::Destination, source: core::reindex::Source) -> Reindex {
        Reindex {
            dest,
            conflicts: None,
            max_docs: None,
            script: None,
            size: None,
            source,
        }
    }
}
