/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteStoreTranslogStats {  /// Statistics related to uploads to the remote translog store.
    #[serde(rename = "upload")]
    pub upload: common::RemoteStoreTranslogUploadStats,
}

impl RemoteStoreTranslogStats {
    
    pub fn new(upload: common::RemoteStoreTranslogUploadStats) -> RemoteStoreTranslogStats {
        RemoteStoreTranslogStats {
            upload,
        }
    }
}
