/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestStats {
    #[serde(rename = "current", default, skip_serializing_if = "Option::is_none")]
    pub current: Option<u32>,  /// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
  /// `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
    #[serde(rename = "time", default, skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "total", default, skip_serializing_if = "Option::is_none")]
    pub total: Option<u32>,
    #[serde(rename = "time_in_millis", default, skip_serializing_if = "Option::is_none")]
    pub time_in_millis: Option<String>,
}

impl RequestStats {
    
    pub fn new() -> RequestStats {
        RequestStats {
            current: None,
            time: None,
            total: None,
            time_in_millis: None,
        }
    }
}
