/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceStat {
    #[serde(rename = "cpu_time_in_nanos")]
    pub cpu_time_in_nanos: String,
    #[serde(rename = "memory_in_bytes")]
    pub memory_in_bytes: u32,
}

impl ResourceStat {
    
    pub fn new(cpu_time_in_nanos: String, memory_in_bytes: u32) -> ResourceStat {
        ResourceStat {
            cpu_time_in_nanos,
            memory_in_bytes,
        }
    }
}
