/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Retries {
    #[serde(rename = "bulk")]
    pub bulk: u32,
    #[serde(rename = "search")]
    pub search: u32,
}

impl Retries {
    
    pub fn new(bulk: u32, search: u32) -> Retries {
        Retries {
            bulk,
            search,
        }
    }
}
