/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlicedScroll {
    #[serde(rename = "max")]
    pub max: u32,
    #[serde(rename = "id")]
    pub id: u32,  /// The path to a field or an array of paths. Some APIs support wildcards in the path, which allows you to select multiple fields.
    #[serde(rename = "field", default, skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
}

impl SlicedScroll {
    
    pub fn new(max: u32, id: u32) -> SlicedScroll {
        SlicedScroll {
            max,
            id,
            field: None,
        }
    }
}
