/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoredScript {
    #[serde(rename = "lang")]
    pub lang: common::ScriptLanguage,  /// The script source.
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "options", default, skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
}

impl StoredScript {
    
    pub fn new(lang: common::ScriptLanguage, source: String) -> StoredScript {
        StoredScript {
            lang,
            source,
            options: None,
        }
    }
}
