/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preview {
    #[serde(rename = "documents", default, skip_serializing_if = "Option::is_none")]
    pub documents: Option<Vec<serde_json::Value>>,
}

impl Preview {
    
    pub fn new() -> Preview {
        Preview {
            documents: None,
        }
    }
}
