/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::transforms;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedule {
    #[serde(rename = "interval")]
    pub interval: transforms::ScheduleInterval,
}

impl Schedule {
    
    pub fn new(interval: transforms::ScheduleInterval) -> Schedule {
        Schedule {
            interval,
        }
    }
}
