/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::sql;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlSettingsValue {
    #[serde(rename = "transient", default, skip_serializing_if = "Option::is_none")]
    pub transient: Option<sql::Transient>,
}

impl SqlSettingsValue {
    
    pub fn new() -> SqlSettingsValue {
        SqlSettingsValue {
            transient: None,
        }
    }
}
