/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlCloseResponse {
    #[serde(rename = "succeeded", default, skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<bool>,
}

impl SqlCloseResponse {
    
    pub fn new() -> SqlCloseResponse {
        SqlCloseResponse {
            succeeded: None,
        }
    }
}
