/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::security;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "opendistro_security_roles", default, skip_serializing_if = "Option::is_none")]
    pub opendistro_security_roles: Option<Vec<String>>,
    #[serde(rename = "hash", default, skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "hidden", default, skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(rename = "password", default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "backend_roles", default, skip_serializing_if = "Option::is_none")]
    pub backend_roles: Option<Vec<String>>,
    #[serde(rename = "attributes", default, skip_serializing_if = "Option::is_none")]
    pub attributes: Option<security::UserAttributes>,
    #[serde(rename = "static", default, skip_serializing_if = "Option::is_none")]
    pub r#static: Option<bool>,
    #[serde(rename = "reserved", default, skip_serializing_if = "Option::is_none")]
    pub reserved: Option<bool>,
    #[serde(rename = "description", default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl User {
    
    pub fn new() -> User {
        User {
            opendistro_security_roles: None,
            hash: None,
            hidden: None,
            password: None,
            backend_roles: None,
            attributes: None,
            r#static: None,
            reserved: None,
            description: None,
        }
    }
}
