/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WhoAmI {
    #[serde(rename = "is_node_certificate_request", default, skip_serializing_if = "Option::is_none")]
    pub is_node_certificate_request: Option<bool>,
    #[serde(rename = "is_admin", default, skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<bool>,
}

impl WhoAmI {
    
    pub fn new() -> WhoAmI {
        WhoAmI {
            is_node_certificate_request: None,
            is_admin: None,
        }
    }
}
