/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::insights;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopQueriesResponse {
    #[serde(rename = "top_queries")]
    pub top_queries: Vec<insights::TopQuery>,
}

impl TopQueriesResponse {
    
    pub fn new(top_queries: Vec<insights::TopQuery>) -> TopQueriesResponse {
        TopQueriesResponse {
            top_queries,
        }
    }
}
