/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

pub mod index_segment;
pub use self::index_segment::IndexSegment;

pub mod segment;
pub use self::segment::Segment;

pub mod shard_segment_routing;
pub use self::shard_segment_routing::ShardSegmentRouting;

pub mod shards_segment;
pub use self::shards_segment::ShardsSegment;
