/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

mod overlapping;
pub use self::overlapping::Overlapping;

mod template;
pub use self::template::Template;

mod simulate_template;
pub use self::simulate_template::SimulateTemplate;
