/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Overlapping {
    #[serde(rename = "index_patterns")]
    pub index_patterns: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
}

impl Overlapping {
    
    pub fn new(index_patterns: Vec<String>, name: String) -> Overlapping {
        Overlapping {
            index_patterns,
            name,
        }
    }
}
