/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsStoreFs {
    #[serde(rename = "fs_lock", default, skip_serializing_if = "Option::is_none")]
    pub fs_lock: Option<String>,
}

impl IndexSettingsStoreFs {
    pub fn new() -> IndexSettingsStoreFs {
        IndexSettingsStoreFs { fs_lock: None }
    }
}
