/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsSimilarityDfi {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "independence_measure")]
    pub independence_measure: String,
}

impl IndexSettingsSimilarityDfi {
    pub fn new(r#type: String, independence_measure: String) -> IndexSettingsSimilarityDfi {
        IndexSettingsSimilarityDfi {
            r#type,
            independence_measure,
        }
    }
}
