/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsSimilarityLmd {
    #[serde(rename = "mu")]
    pub mu: f64,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl IndexSettingsSimilarityLmd {
    pub fn new(mu: f64, r#type: String) -> IndexSettingsSimilarityLmd {
        IndexSettingsSimilarityLmd { mu, r#type }
    }
}
