/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use crate::indices;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsStarTreeField {
    /// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
    /// this behavior while keeping the semantics of the field type.
    ///
    /// Depending on the target language, code generators can keep the union or remove it and leniently parse
    /// strings to the target type.
    #[serde(
        rename = "max_dimensions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_dimensions: Option<common::StringifiedInteger>,
    /// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
    /// this behavior while keeping the semantics of the field type.
    ///
    /// Depending on the target language, code generators can keep the union or remove it and leniently parse
    /// strings to the target type.
    #[serde(
        rename = "max_date_intervals",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_date_intervals: Option<common::StringifiedInteger>,
    #[serde(rename = "default", default, skip_serializing_if = "Option::is_none")]
    pub default: Option<indices::IndexSettingsStarTreeFieldDefault>,
    /// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
    /// this behavior while keeping the semantics of the field type.
    ///
    /// Depending on the target language, code generators can keep the union or remove it and leniently parse
    /// strings to the target type.
    #[serde(
        rename = "max_base_metrics",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_base_metrics: Option<common::StringifiedInteger>,
}

impl IndexSettingsStarTreeField {
    pub fn new() -> IndexSettingsStarTreeField {
        IndexSettingsStarTreeField {
            max_dimensions: None,
            max_date_intervals: None,
            default: None,
            max_base_metrics: None,
        }
    }
}
