/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsMergeLogByteSizePolicy {
    /// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
    /// this behavior while keeping the semantics of the field type.
    ///
    /// Depending on the target language, code generators can keep the union or remove it and leniently parse
    /// strings to the target type.
    #[serde(
        rename = "max_merged_docs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_merged_docs: Option<common::StringifiedInteger>,
    #[serde(
        rename = "max_merge_segment",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_merge_segment: Option<String>,
    #[serde(rename = "min_merge", default, skip_serializing_if = "Option::is_none")]
    pub min_merge: Option<String>,
    #[serde(
        rename = "max_merge_segment_forced_merge",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_merge_segment_forced_merge: Option<String>,
    /// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
    /// this behavior while keeping the semantics of the field type.
    ///
    /// Depending on the target language, code generators can keep the union or remove it and leniently parse
    /// strings to the target type.
    #[serde(
        rename = "merge_factor",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub merge_factor: Option<common::StringifiedInteger>,
    #[serde(
        rename = "no_cfs_ratio",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub no_cfs_ratio: Option<common::StringifiedDouble>,
}

impl IndexSettingsMergeLogByteSizePolicy {
    pub fn new() -> IndexSettingsMergeLogByteSizePolicy {
        IndexSettingsMergeLogByteSizePolicy {
            max_merged_docs: None,
            max_merge_segment: None,
            min_merge: None,
            max_merge_segment_forced_merge: None,
            merge_factor: None,
            no_cfs_ratio: None,
        }
    }
}
