/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::indices;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsIndexing {
    #[serde(rename = "slowlog", default, skip_serializing_if = "Option::is_none")]
    pub slowlog: Option<indices::IndexingSlowlog>,
}

impl IndexSettingsIndexing {
    pub fn new() -> IndexSettingsIndexing {
        IndexSettingsIndexing { slowlog: None }
    }
}
