/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexSettingsSimilarityDfr {
    #[serde(rename = "after_effect")]
    pub after_effect: String,
    #[serde(rename = "normalization")]
    pub normalization: String,
    #[serde(rename = "basic_model")]
    pub basic_model: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl IndexSettingsSimilarityDfr {
    pub fn new(
        after_effect: String,
        normalization: String,
        basic_model: String,
        r#type: String,
    ) -> IndexSettingsSimilarityDfr {
        IndexSettingsSimilarityDfr {
            after_effect,
            normalization,
            basic_model,
            r#type,
        }
    }
}
