/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::indices;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSlowlogThresholds {
    #[serde(rename = "query", default, skip_serializing_if = "Option::is_none")]
    pub query: Option<indices::SlowlogThresholdLevels>,
    #[serde(rename = "fetch", default, skip_serializing_if = "Option::is_none")]
    pub fetch: Option<indices::SlowlogThresholdLevels>,
}

impl SearchSlowlogThresholds {
    pub fn new() -> SearchSlowlogThresholds {
        SearchSlowlogThresholds {
            query: None,
            fetch: None,
        }
    }
}
