/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

/// SplitRequestBodyJson
/// The configuration for the target index (`settings` and `aliases`)

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SplitRequestBodyJson {
    /// Aliases for the resulting index.
    #[serde(rename = "aliases", default, skip_serializing_if = "Option::is_none")]
    pub aliases: Option<serde_json::Value>,
    /// Configuration options for the target index.
    #[serde(rename = "settings", default, skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

impl SplitRequestBodyJson {
    /// The configuration for the target index (`settings` and `aliases`)
    pub fn new() -> SplitRequestBodyJson {
        SplitRequestBodyJson {
            aliases: None,
            settings: None,
        }
    }
}
