/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::indices;
use serde::{Deserialize, Serialize};

/// UpdateAliasesRequestBodyJson
/// The definition of `actions` to perform

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAliasesRequestBodyJson {
    /// Actions to perform.
    #[serde(rename = "actions", default, skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<indices::update_aliases::Action>>,
}

impl UpdateAliasesRequestBodyJson {
    /// The definition of `actions` to perform
    pub fn new() -> UpdateAliasesRequestBodyJson {
        UpdateAliasesRequestBodyJson { actions: None }
    }
}
