/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::indices;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoveryIndexStatus {  /// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
  /// `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
    #[serde(rename = "total_time", default, skip_serializing_if = "Option::is_none")]
    pub total_time: Option<String>,  /// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
  /// `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
    #[serde(rename = "target_throttle_time", default, skip_serializing_if = "Option::is_none")]
    pub target_throttle_time: Option<String>,
    #[serde(rename = "target_throttle_time_in_millis")]
    pub target_throttle_time_in_millis: String,
    #[serde(rename = "bytes", default, skip_serializing_if = "Option::is_none")]
    pub bytes: Option<indices::recovery::RecoveryBytes>,  /// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
  /// `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
    #[serde(rename = "source_throttle_time", default, skip_serializing_if = "Option::is_none")]
    pub source_throttle_time: Option<String>,
    #[serde(rename = "total_time_in_millis")]
    pub total_time_in_millis: String,
    #[serde(rename = "source_throttle_time_in_millis")]
    pub source_throttle_time_in_millis: String,
    #[serde(rename = "size")]
    pub size: indices::recovery::RecoveryBytes,
    #[serde(rename = "files")]
    pub files: indices::recovery::RecoveryFiles,
}

impl RecoveryIndexStatus {
    
    pub fn new(target_throttle_time_in_millis: String, total_time_in_millis: String, source_throttle_time_in_millis: String, size: indices::recovery::RecoveryBytes, files: indices::recovery::RecoveryFiles) -> RecoveryIndexStatus {
        RecoveryIndexStatus {
            total_time: None,
            target_throttle_time: None,
            target_throttle_time_in_millis,
            bytes: None,
            source_throttle_time: None,
            total_time_in_millis,
            source_throttle_time_in_millis,
            size,
            files,
        }
    }
}
