/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddPolicyRequest {
    #[serde(rename = "policy_id")]
    pub policy_id: String,
}

impl AddPolicyRequest {
    
    pub fn new(policy_id: String) -> AddPolicyRequest {
        AddPolicyRequest {
            policy_id,
        }
    }
}
