/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshSearchAnalyzersResponseDetails {
    #[serde(rename = "refreshed_analyzers", default, skip_serializing_if = "Option::is_none")]
    pub refreshed_analyzers: Option<Vec<String>>,
    #[serde(rename = "index", default, skip_serializing_if = "Option::is_none")]
    pub index: Option<String>,
}

impl RefreshSearchAnalyzersResponseDetails {
    
    pub fn new() -> RefreshSearchAnalyzersResponseDetails {
        RefreshSearchAnalyzersResponseDetails {
            refreshed_analyzers: None,
            index: None,
        }
    }
}
