/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::core;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextMethod {
    #[serde(rename = "return_type")]
    pub return_type: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "params")]
    pub params: Vec<core::get_script_context::ContextMethodParam>,
}

impl ContextMethod {
    
    pub fn new(return_type: String, name: String, params: Vec<core::get_script_context::ContextMethodParam>) -> ContextMethod {
        ContextMethod {
            return_type,
            name,
            params,
        }
    }
}
