/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

pub mod health_response_body;
pub use self::health_response_body::HealthResponseBody;

pub mod index_health_stats;
pub use self::index_health_stats::IndexHealthStats;

pub mod shard_health_stats;
pub use self::shard_health_stats::ShardHealthStats;
