/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoSettingsTransportTypeConfigValue {
    #[serde(rename = "default", default, skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

impl NodeInfoSettingsTransportTypeConfigValue {
    
    pub fn new() -> NodeInfoSettingsTransportTypeConfigValue {
        NodeInfoSettingsTransportTypeConfigValue {
            default: None,
        }
    }
}
