/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoIngestProcessor {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl NodeInfoIngestProcessor {
    
    pub fn new(r#type: String) -> NodeInfoIngestProcessor {
        NodeInfoIngestProcessor {
            r#type,
        }
    }
}
