/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoSettingsNode {
    #[serde(rename = "attr", default, skip_serializing_if = "Option::is_none")]
    pub attr: Option<serde_json::Value>,
    #[serde(rename = "max_local_storage_nodes", default, skip_serializing_if = "Option::is_none")]
    pub max_local_storage_nodes: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
}

impl NodeInfoSettingsNode {
    
    pub fn new(name: String) -> NodeInfoSettingsNode {
        NodeInfoSettingsNode {
            attr: None,
            max_local_storage_nodes: None,
            name,
        }
    }
}
