/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoRepositoriesUrl {
    #[serde(rename = "allowed_urls")]
    pub allowed_urls: String,
}

impl NodeInfoRepositoriesUrl {
    
    pub fn new(allowed_urls: String) -> NodeInfoRepositoriesUrl {
        NodeInfoRepositoriesUrl {
            allowed_urls,
        }
    }
}
