/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoScript {
    #[serde(rename = "allowed_types")]
    pub allowed_types: String,
    #[serde(rename = "disable_max_compilations_rate")]
    pub disable_max_compilations_rate: String,
}

impl NodeInfoScript {
    
    pub fn new(allowed_types: String, disable_max_compilations_rate: String) -> NodeInfoScript {
        NodeInfoScript {
            allowed_types,
            disable_max_compilations_rate,
        }
    }
}
