/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::nodes;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoIngest {
    #[serde(rename = "processors")]
    pub processors: Vec<nodes::info::NodeInfoIngestProcessor>,
}

impl NodeInfoIngest {
    
    pub fn new(processors: Vec<nodes::info::NodeInfoIngestProcessor>) -> NodeInfoIngest {
        NodeInfoIngest {
            processors,
        }
    }
}
