/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::nodes;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoSettingsTransport {
    #[serde(rename = "type")]
    pub r#type: nodes::info::NodeInfoSettingsTransportType,
    #[serde(rename = "type.default", default, skip_serializing_if = "Option::is_none")]
    pub type_default: Option<String>,
}

impl NodeInfoSettingsTransport {
    
    pub fn new(r#type: nodes::info::NodeInfoSettingsTransportType) -> NodeInfoSettingsTransport {
        NodeInfoSettingsTransport {
            r#type,
            type_default: None,
        }
    }
}
