/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfoAction {
    #[serde(rename = "destructive_requires_name")]
    pub destructive_requires_name: String,
}

impl NodeInfoAction {
    
    pub fn new(destructive_requires_name: String) -> NodeInfoAction {
        NodeInfoAction {
            destructive_requires_name,
        }
    }
}
