/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

pub mod delete_operation;
pub use self::delete_operation::DeleteOperation;

pub mod operation_base;
pub use self::operation_base::OperationBase;

pub mod operation_container;
pub use self::operation_container::OperationContainer;

pub mod response_item;
pub use self::response_item::ResponseItem;

pub mod update_action;
pub use self::update_action::UpdateAction;
