/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */
use crate::{
    common::query_dsl::{DateDecayPlacement, GeoDecayPlacement, NumericDecayPlacement},
};
use crate::common;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DecayPlacement {
    DateDecayPlacementValue(DateDecayPlacement),
    GeoDecayPlacementValue(GeoDecayPlacement),
    NumericDecayPlacementValue(NumericDecayPlacement),
}
