/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptScoreFunction {
    #[serde(rename = "script")]
    pub script: common::Script,
}

impl ScriptScoreFunction {
    
    pub fn new(script: common::Script) -> ScriptScoreFunction {
        ScriptScoreFunction {
            script,
        }
    }
}
