/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

/// SimpleQueryStringFlags
/// Query flags can be either a single flag or a combination of flags (e.g. `OR|AND|PREFIX`).
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SimpleQueryStringFlags {
    MultipleValue(Vec<String>),
    SimpleQueryStringFlagValue(String),
}
