/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::cluster;
use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterIndices {
    #[serde(rename = "store", default, skip_serializing_if = "Option::is_none")]
    pub store: Option<common::StoreStats>,  /// Total number of indexes with shards assigned to selected nodes.
    #[serde(rename = "count", default, skip_serializing_if = "Option::is_none")]
    pub count: Option<u32>,
    #[serde(rename = "mappings", default, skip_serializing_if = "Option::is_none")]
    pub mappings: Option<cluster::stats::FieldTypesMappings>,  /// Contains statistics about analyzers and analyzer components used in selected nodes.
    #[serde(rename = "versions", default, skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<cluster::stats::IndicesVersions>>,
    #[serde(rename = "query_cache", default, skip_serializing_if = "Option::is_none")]
    pub query_cache: Option<common::QueryCacheStats>,
    #[serde(rename = "docs", default, skip_serializing_if = "Option::is_none")]
    pub docs: Option<common::DocStats>,
    #[serde(rename = "completion", default, skip_serializing_if = "Option::is_none")]
    pub completion: Option<common::CompletionStats>,
    #[serde(rename = "fielddata", default, skip_serializing_if = "Option::is_none")]
    pub fielddata: Option<common::FielddataStats>,
    #[serde(rename = "segments", default, skip_serializing_if = "Option::is_none")]
    pub segments: Option<common::SegmentsStats>,
    #[serde(rename = "analysis", default, skip_serializing_if = "Option::is_none")]
    pub analysis: Option<cluster::stats::CharFilterTypes>,
    #[serde(rename = "shards", default, skip_serializing_if = "Option::is_none")]
    pub shards: Option<cluster::stats::ClusterIndicesShards>,
}

impl ClusterIndices {
    
    pub fn new() -> ClusterIndices {
        ClusterIndices {
            store: None,
            count: None,
            mappings: None,
            versions: None,
            query_cache: None,
            docs: None,
            completion: None,
            fielddata: None,
            segments: None,
            analysis: None,
            shards: None,
        }
    }
}
