/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::cluster;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldTypesMappings {  /// Contains statistics about field data types used in selected nodes.
    #[serde(rename = "field_types")]
    pub field_types: Vec<cluster::stats::FieldTypes>,
}

impl FieldTypesMappings {
    
    pub fn new(field_types: Vec<cluster::stats::FieldTypes>) -> FieldTypesMappings {
        FieldTypesMappings {
            field_types,
        }
    }
}
