/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::cluster;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingTasksResponse {
    #[serde(rename = "tasks")]
    pub tasks: Vec<cluster::pending_tasks::PendingTask>,
}

impl PendingTasksResponse {
    
    pub fn new(tasks: Vec<cluster::pending_tasks::PendingTask>) -> PendingTasksResponse {
        PendingTasksResponse {
            tasks,
        }
    }
}
