/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};

/// PutSettingsRequestBodyJson
/// The cluster settings to update.


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutSettingsRequestBodyJson {
    #[serde(rename = "persistent", default, skip_serializing_if = "Option::is_none")]
    pub persistent: Option<serde_json::Value>,
    #[serde(rename = "transient", default, skip_serializing_if = "Option::is_none")]
    pub transient: Option<serde_json::Value>,
}

impl PutSettingsRequestBodyJson {
      /// The cluster settings to update.
    pub fn new() -> PutSettingsRequestBodyJson {
        PutSettingsRequestBodyJson {
            persistent: None,
            transient: None,
        }
    }
}
