/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnMeta {
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,  /// The column type.
    #[serde(rename = "column_type", default, skip_serializing_if = "Option::is_none")]
    pub column_type: Option<String>,
}

impl ColumnMeta {
    
    pub fn new() -> ColumnMeta {
        ColumnMeta {
            name: None,
            column_type: None,
        }
    }
}
