/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::ml;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InputQuery {  /// The query.
    #[serde(rename = "query", default, skip_serializing_if = "Option::is_none")]
    pub query: Option<ml::Query>,  /// The size of the query.
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<u32>,  /// The source fields
    #[serde(rename = "_source", default, skip_serializing_if = "Option::is_none")]
    pub source: Option<Vec<String>>,
}

impl InputQuery {
    
    pub fn new() -> InputQuery {
        InputQuery {
            query: None,
            size: None,
            source: None,
        }
    }
}
