/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

/// MatchAllQuery
/// The match all query.


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchAllQuery {
}

impl MatchAllQuery {
      /// The match all query.
    pub fn new() -> MatchAllQuery {
        MatchAllQuery {
        }
    }
}
