/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrainParameters {  /// The distance type.
    #[serde(rename = "distance_type", default, skip_serializing_if = "Option::is_none")]
    pub distance_type: Option<String>,  /// The iterations.
    #[serde(rename = "iterations", default, skip_serializing_if = "Option::is_none")]
    pub iterations: Option<u32>,  /// The centroids.
    #[serde(rename = "centroids", default, skip_serializing_if = "Option::is_none")]
    pub centroids: Option<u32>,
}

impl TrainParameters {
    
    pub fn new() -> TrainParameters {
        TrainParameters {
            distance_type: None,
            iterations: None,
            centroids: None,
        }
    }
}
