/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};

/// Type
/// The type.


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Type {  /// The agent type.
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl Type {
      /// The type.
    pub fn new() -> Type {
        Type {
            value: None,
        }
    }
}
