/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnloadModelRequestBodyJson {
    #[serde(rename = "model_ids", default, skip_serializing_if = "Option::is_none")]
    pub model_ids: Option<Vec<String>>,
    #[serde(rename = "node_ids", default, skip_serializing_if = "Option::is_none")]
    pub node_ids: Option<Vec<String>>,
}

impl UnloadModelRequestBodyJson {
    
    pub fn new() -> UnloadModelRequestBodyJson {
        UnloadModelRequestBodyJson {
            model_ids: None,
            node_ids: None,
        }
    }
}
