/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Values {  /// The value.
    #[serde(rename = "value", default, skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,  /// The column type.
    #[serde(rename = "column_type", default, skip_serializing_if = "Option::is_none")]
    pub column_type: Option<String>,
}

impl Values {
    
    pub fn new() -> Values {
        Values {
            value: None,
            column_type: None,
        }
    }
}
