/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::common;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesResponseBase {
    #[serde(rename = "_nodes", default, skip_serializing_if = "Option::is_none")]
    pub nodes: Option<common::NodeStatistics>,
}

impl NodesResponseBase {
    
    pub fn new() -> NodesResponseBase {
        NodesResponseBase {
            nodes: None,
        }
    }
}
