/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use crate::observability;
use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SavedVisualization {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "selected_date_range")]
    pub selected_date_range: observability::SelectedDateRange,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "selected_fields")]
    pub selected_fields: observability::SelectedFields,
    #[serde(rename = "selected_timestamp")]
    pub selected_timestamp: observability::SelectedTimestamp,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SavedVisualization {
    
    pub fn new(description: String, selected_date_range: observability::SelectedDateRange, name: String, query: String, selected_fields: observability::SelectedFields, selected_timestamp: observability::SelectedTimestamp, r#type: String) -> SavedVisualization {
        SavedVisualization {
            description,
            selected_date_range,
            name,
            query,
            selected_fields,
            selected_timestamp,
            r#type,
        }
    }
}
