/*
 * opensearch-client
 *
 * Rust Client for OpenSearch
 *
 * The version of the OpenAPI document: 3.1.0
 * Contact: alberto.paro@gmail.com
 * Generated by Paro OpenAPI Generator
 */

use serde::{Deserialize, Serialize};




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedDateRange {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "start")]
    pub start: String,
    #[serde(rename = "end")]
    pub end: String,
}

impl SelectedDateRange {
    
    pub fn new(text: String, start: String, end: String) -> SelectedDateRange {
        SelectedDateRange {
            text,
            start,
            end,
        }
    }
}
